##############################################
# 服务端配置
##############################################
server:
  port: 70

##############################################
# spring
##############################################
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/snboot?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ENC(x0jY0g478sC7qMnAMOmvgA==)
    password: ENC(x0jY0g478sC7qMnAMOmvgA==)

  ##############################################
  # redis配置
  ##############################################
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 1000ms

  ##############################################
  # rabbitmq配置
  ##############################################
  rabbitmq:
    # rabbitmq服务器地址
    host: 127.0.0.1
    # rabbitmq服务器连接端口
    port: 5672
    # rabbitmq服务器连接账号密码
    username: ENC(x0jY0g478sC7qMnAMOmvgA==)
    password: ENC(trImmrZmCdTYPOY2+ksnTw==)
    listener:
      simple:
        # 自动签收auto、手动manual
        acknowledge-mode: manual

##############################################
# 日志配置
##############################################
logging:
  level:
    com.alibaba.druid: debug
    org.nutz: debug
    com.yunqi: debug
